# Generated by Django 6.0.2 on 2026-02-18 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_account_expense_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('BLOCKED_DUPLICATE', 'Blocked duplicate')], default='IMPORTED', max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('rows_detected', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_imports', to='tracker.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
